/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["healthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_emails"];
    put?: never;
    post: operations["add"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/verifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["confirm_verification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["make_primary"];
    post?: never;
    delete: operations["remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/{id}/verifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_verification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/jwks.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["jwks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/magic-links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_magic_link"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/apple/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["apple_callback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["authorize"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/{provider}/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/password-resets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_password_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_sessions"];
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_current"];
    put?: never;
    post?: never;
    delete: operations["delete_current"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_by_id"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * POST /v1/tokens — issue a short-lived JWT access token.
     *     Requires `jwt_enabled = true` in app_config; returns 400 otherwise.
     */
    post: operations["issue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/totp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["confirm_enrollment"];
    post: operations["begin_enrollment"];
    delete: operations["disable"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["update_me"];
    trace?: never;
  };
  "/v1/webauthn/authentications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["finish_webauthn_authentication"];
    post: operations["begin_webauthn_authentication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/webauthn/credentials": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_webauthn_credentials"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/webauthn/credentials/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_webauthn_credential"];
    options?: never;
    head?: never;
    patch: operations["update_webauthn_credential"];
    trace?: never;
  };
  "/v1/webauthn/registrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["finish_webauthn_registration"];
    post: operations["begin_webauthn_registration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddRequest: {
      email: string;
    };
    AppleCallbackForm: {
      code: string;
      state: string;
      user?: string | null;
    };
    AuthResponse: {
      email: components["schemas"]["EmailBody"];
      session: components["schemas"]["SessionBody"];
      tenant: components["schemas"]["TenantBody"];
      user: components["schemas"]["UserBody"];
    };
    BeginResponse: {
      /** @description WebAuthn options object — pass directly to the browser's WebAuthn API. */
      options: Record<string, never>;
      /** @description Opaque state token; include in the corresponding finish request. */
      state_token: string;
    };
    ConfirmRequest: {
      code: string;
    };
    ConfirmVerificationRequest: {
      token: string;
    };
    ConfirmVerificationResponse: {
      /** Format: date-time */
      verified_at: string;
    };
    CredentialRecord: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      last_used_at?: string | null;
      nickname?: string | null;
    };
    CurrentSessionResponse: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      ip_address?: string | null;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: uuid */
      token_id: string;
      user_agent?: string | null;
    };
    EmailBody: {
      email: string;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      verified_at?: string | null;
    };
    EmailRecord: {
      email: string;
      /** Format: uuid */
      id: string;
      is_primary: boolean;
      /** Format: date-time */
      verified_at?: string | null;
    };
    EnrollmentResponse: {
      /** Format: uuid */
      factor_id: string;
      provisioning_uri: string;
      qr_data_url: string;
      recovery_codes: string[];
      secret_b32: string;
    };
    /** @description Wire-format error body returned on all non-2xx responses. */
    ErrorBody: {
      /** @description Machine-readable error code, e.g. `"invalid_credentials"`. */
      code: string;
      /** @description Human-readable description. */
      message: string;
    };
    /** @description Top-level error envelope for all API error responses. */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    FinishAuthenticationRequest: {
      /** @description WebAuthn `PublicKeyCredential` response from the browser. */
      credential: Record<string, never>;
      state_token: string;
    };
    FinishRegistrationRequest: {
      /** @description WebAuthn `PublicKeyCredential` response from the browser. */
      credential: Record<string, never>;
      nickname?: string | null;
      state_token: string;
    };
    HealthzResponse: {
      status: string;
      version: string;
    };
    Jwk: {
      alg: string;
      crv: string;
      kid: string;
      kty: string;
      use: string;
      x: string;
    };
    JwkSet: {
      keys: components["schemas"]["Jwk"][];
    };
    LoginRequest: {
      email: string;
      /** @enum {string} */
      grant_type: "password";
      password: string;
    } | {
      /** @enum {string} */
      grant_type: "magic_link";
      token: string;
    } | {
      /** @enum {string} */
      grant_type: "password_reset";
      new_password: string;
      token: string;
    } | {
      /** @enum {string} */
      grant_type: "email_change";
      token: string;
    } | {
      code: string;
      /** @enum {string} */
      grant_type: "totp_step_up";
      step_up_token: string;
    } | {
      code: string;
      /** @enum {string} */
      grant_type: "totp_recovery";
      step_up_token: string;
    };
    MagicLinkRequest: {
      email: string;
    };
    MagicLinkResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to exchange via `POST /v1/sessions` with `grant_type=magic_link`. */
      token: string;
    };
    MeResponse: {
      email: components["schemas"]["EmailBody"];
      tenant: components["schemas"]["TenantBody"];
      user: components["schemas"]["UserBody"];
    };
    OttTokenResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to use in the corresponding session grant. */
      token: string;
    };
    PasswordResetRequest: {
      email: string;
    };
    PasswordResetResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to exchange via `POST /v1/sessions` with `grant_type=password_reset`. */
      token: string;
    };
    RegisteredCredential: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      nickname?: string | null;
    };
    SessionBody: {
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      /** @description Opaque bearer token — store securely, transmit as `Authorization: Bearer <token>`. */
      token: string;
    };
    SessionListItem: {
      /** Format: date-time */
      created_at: string;
      /** @description Whether this is the caller's current session. */
      current: boolean;
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      ip_address?: string | null;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: uuid */
      token_id: string;
      user_agent?: string | null;
    };
    SessionsResponse: {
      sessions: components["schemas"]["SessionListItem"][];
    };
    SignupRequest: {
      display_name?: string | null;
      email: string;
      password: string;
    };
    /** @description Returned when the user has TOTP enrolled — caller must complete the step-up flow. */
    StepUpResponse: {
      /** @description The MFA method required, e.g. `"totp"`. */
      step_up_required: string;
      /** @description Short-lived signed token to present when completing the step-up. */
      step_up_token: string;
    };
    TenantBody: {
      /** Format: uuid */
      id: string;
      name: string;
      slug: string;
    };
    TokenResponse: {
      access_token: string;
      /**
       * Format: int32
       * @description Lifetime in seconds.
       */
      expires_in: number;
      token_type: string;
    };
    UpdateCredentialRequest: {
      nickname: string;
    };
    UpdateUser: {
      avatar_url?: string | null;
      display_name?: string | null;
    };
    UserBody: {
      avatar_url?: string | null;
      /** Format: date-time */
      created_at: string;
      display_name?: string | null;
      /** Format: uuid */
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthzResponse"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthzResponse"];
        };
      };
    };
  };
  list_emails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailRecord"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  add: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OttTokenResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirm_verification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmVerificationRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            components["schemas"]["ConfirmVerificationResponse"];
        };
      };
      /** @description Invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  make_primary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email set as primary */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email not found or not verified */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot remove primary email */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_verification: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OttTokenResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email not found or already verified */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  jwks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          /** @description public, max-age=3600, must-revalidate */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JwkSet"];
        };
      };
    };
  };
  create_magic_link: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MagicLinkRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MagicLinkResponse"];
        };
      };
      /** @description No account with that email */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  apple_callback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded":
          components["schemas"]["AppleCallbackForm"];
      };
    };
    responses: {
      /** @description Redirect to redirect_url with token and expires_at query params */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid state or Apple error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authorize: {
    parameters: {
      query: {
        /** @description URL to redirect to after authentication */
        redirect_url: string;
      };
      header?: never;
      path: {
        /** @description OAuth provider slug, e.g. `github`, `google` */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to OAuth provider */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Provider not configured */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  callback: {
    parameters: {
      query: {
        /** @description Authorization code from provider */
        code: string;
        /** @description PKCE state JWT */
        state: string;
      };
      header?: never;
      path: {
        /** @description OAuth provider slug */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to redirect_url with token and expires_at query params */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid state or provider error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasswordResetResponse"];
        };
      };
      /** @description No account with that email or no password identity */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionsResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description MFA step-up required */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepUpResponse"];
        };
      };
      /** @description Session created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid credentials or token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentSessionResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Session ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  issue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description JWT not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirm_enrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmRequest"];
      };
    };
    responses: {
      /** @description TOTP enrollment confirmed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  begin_enrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EnrollmentResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  disable: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description TOTP disabled */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUser"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  finish_webauthn_authentication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          components["schemas"]["FinishAuthenticationRequest"];
      };
    };
    responses: {
      /** @description MFA step-up required */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepUpResponse"];
        };
      };
      /** @description Authentication successful */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  begin_webauthn_authentication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BeginResponse"];
        };
      };
    };
  };
  list_webauthn_credentials: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CredentialRecord"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_webauthn_credential: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Credential ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Credential deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_webauthn_credential: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Credential ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCredentialRequest"];
      };
    };
    responses: {
      /** @description Credential updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  finish_webauthn_registration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FinishRegistrationRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisteredCredential"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  begin_webauthn_registration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BeginResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
