/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["healthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/relation-partitions/{object_type}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Ensure a dedicated LIST partition exists for `object_type`.
     * @description Idempotent — safe to call multiple times. Existing rows in the default
     *     partition are moved to the new partition atomically.
     */
    put: operations["ensure_partition"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check whether the current session user (or an explicit user) has a permission
     *     on a resource. Uses a bundled session-validation + authz CTE for one DB round-trip
     *     when checking the current session user.
     */
    get: operations["check_permission"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/expansions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Expand a relation: return all subjects who hold the given relation on the object.
     *     Resolves subject sets recursively.
     */
    get: operations["expand_relation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/lookups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all objects of the given type that the current user (or an explicit user)
     *     can access via the resolved roles for a permission.
     */
    get: operations["lookup_objects"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/relations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Write a single relation tuple. Idempotent — duplicate writes are silently ignored. */
    post: operations["write_relation"];
    /** Delete a single relation tuple. */
    delete: operations["delete_relation"];
    options?: never;
    head?: never;
    /** Batch write and/or delete relation tuples in a single transaction. */
    patch: operations["batch_relations"];
    trace?: never;
  };
  "/v1/authz/schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the current authz schema. Returns null if authz is not enabled. */
    get: operations["get_schema"];
    /**
     * Replace the authz schema. Validates and compiles before persisting.
     *     Setting schema to a valid document enables authz; this is the only way to enable it.
     */
    put: operations["put_schema"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/traces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Explain why a permission check returned its result. Runs expand on all relevant
     *     relations and reports which subjects appear, letting you trace a grant or denial.
     */
    get: operations["why_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_emails"];
    put?: never;
    post: operations["add"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/verifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["confirm_verification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["make_primary"];
    post?: never;
    delete: operations["remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/{id}/verifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_verification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/jwks.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["jwks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/magic-links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_magic_link"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/apple/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["apple_callback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["authorize"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/{provider}/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/passkey-authentications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["begin_passkey_authentication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/passkey-registrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["begin_passkey_registration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/passkeys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_passkeys"];
    put?: never;
    post: operations["create_passkey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/passkeys/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_passkey"];
    options?: never;
    head?: never;
    patch: operations["update_passkey"];
    trace?: never;
  };
  "/v1/password-resets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_password_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_sessions"];
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_current"];
    put?: never;
    post?: never;
    delete: operations["delete_current"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_by_id"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * POST /v1/tokens — issue a short-lived JWT access token.
     *     Requires `jwt_enabled = true` in app_config; returns 400 otherwise.
     */
    post: operations["issue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/totp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["begin_enrollment"];
    delete: operations["disable"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/totp/confirmations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["confirm_enrollment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["update_me"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddRequest: {
      email: string;
    };
    AppleCallbackForm: {
      code: string;
      state: string;
      user?: string | null;
    };
    AuthResponse: {
      email: components["schemas"]["EmailBody"];
      session: components["schemas"]["SessionBody"];
      org: components["schemas"]["OrgBody"];
      user: components["schemas"]["UserBody"];
    };
    AuthzSchema: {
      resources: components["schemas"]["ResourceDef"][];
      subject_types?: string[];
      /** Format: int32 */
      version: number;
    };
    BatchRequest: {
      deletes?: components["schemas"]["RelationRequest"][];
      writes?: components["schemas"]["RelationRequest"][];
    };
    BatchResponse: {
      /** Format: int64 */
      deleted: number;
      /** Format: int64 */
      written: number;
    };
    BeginResponse: {
      /** @description WebAuthn options object — pass directly to the browser's WebAuthn API. */
      options: Record<string, never>;
      /** @description Opaque state token; include in the corresponding finish request. */
      state_token: string;
    };
    CheckResponse: {
      allowed: boolean;
    };
    ConfirmRequest: {
      code: string;
    };
    ConfirmVerificationRequest: {
      token: string;
    };
    ConfirmVerificationResponse: {
      /** Format: date-time */
      verified_at: string;
    };
    CredentialRecord: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      last_used_at?: string | null;
      nickname?: string | null;
    };
    CurrentSessionResponse: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      ip_address?: string | null;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: uuid */
      token_id: string;
      user_agent?: string | null;
    };
    EmailBody: {
      email: string;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      verified_at?: string | null;
    };
    EmailRecord: {
      email: string;
      /** Format: uuid */
      id: string;
      is_primary: boolean;
      /** Format: date-time */
      verified_at?: string | null;
    };
    EnrollmentResponse: {
      /** Format: uuid */
      factor_id: string;
      provisioning_uri: string;
      qr_data_url: string;
      recovery_codes: string[];
      secret_b32: string;
    };
    /** @description Wire-format error body returned on all non-2xx responses. */
    ErrorBody: {
      /** @description Machine-readable error code, e.g. `"invalid_credentials"`. */
      code: string;
      /** @description Human-readable description. */
      message: string;
    };
    /** @description Top-level error envelope for all API error responses. */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    ExpandResponse: {
      subjects: components["schemas"]["ExpandSubject"][];
    };
    ExpandSubject: {
      id: string;
      relation: string;
    };
    FinishRegistrationRequest: {
      /** @description WebAuthn `PublicKeyCredential` response from the browser. */
      credential: Record<string, never>;
      nickname?: string | null;
      state_token: string;
    };
    HealthzResponse: {
      status: string;
      version: string;
    };
    HierarchyDef: {
      /** @description The relation name on this resource that points to parent objects. */
      parent_relation: string;
      /** @description The resource type of the parent. */
      parent_resource: string;
    };
    Jwk: {
      alg: string;
      crv: string;
      kid: string;
      kty: string;
      use: string;
      x: string;
    };
    JwkSet: {
      keys: components["schemas"]["Jwk"][];
    };
    LoginRequest:
      | {
        email: string;
        /** @enum {string} */
        grant_type: "password";
        password: string;
      }
      | {
        /** @enum {string} */
        grant_type: "magic_link";
        token: string;
      }
      | {
        /** @enum {string} */
        grant_type: "password_reset";
        new_password: string;
        token: string;
      }
      | {
        /** @enum {string} */
        grant_type: "email_change";
        token: string;
      }
      | {
        code: string;
        /** @enum {string} */
        grant_type: "totp_step_up";
        step_up_token: string;
      }
      | {
        code: string;
        /** @enum {string} */
        grant_type: "totp_recovery";
        step_up_token: string;
      }
      | {
        credential: Record<string, never>;
        /** @enum {string} */
        grant_type: "passkey";
        state_token: string;
      };
    LookupResponse: {
      next_cursor?: string | null;
      object_ids: string[];
    };
    MagicLinkRequest: {
      email: string;
    };
    MagicLinkResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to exchange via `POST /v1/sessions` with `grant_type=magic_link`. */
      token: string;
    };
    MeResponse: {
      email: components["schemas"]["EmailBody"];
      org: components["schemas"]["OrgBody"];
      user: components["schemas"]["UserBody"];
    };
    OttTokenResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to use in the corresponding session grant. */
      token: string;
    };
    PasswordResetRequest: {
      email: string;
    };
    PasswordResetResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to exchange via `POST /v1/sessions` with `grant_type=password_reset`. */
      token: string;
    };
    RegisteredCredential: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      nickname?: string | null;
    };
    RelationObject: {
      id: string;
      type: string;
    };
    RelationRequest: {
      object: components["schemas"]["RelationObject"];
      relation: string;
      subject: components["schemas"]["RelationSubject"];
    };
    RelationSubject: {
      id: string;
      relation?: string | null;
      type?: string | null;
    };
    ResourceDef: {
      hierarchy?: null | components["schemas"]["HierarchyDef"];
      name: string;
      permissions: {
        [key: string]: string[];
      };
      role_hierarchy?: components["schemas"]["RoleEdge"][];
      roles: string[];
    };
    RoleEdge: {
      inferior: string;
      superior: string;
    };
    SessionBody: {
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      /** @description Opaque bearer token — store securely, transmit as `Authorization: Bearer <token>`. */
      token: string;
    };
    SessionListItem: {
      /** Format: date-time */
      created_at: string;
      /** @description Whether this is the caller's current session. */
      current: boolean;
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      ip_address?: string | null;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: uuid */
      token_id: string;
      user_agent?: string | null;
    };
    SessionsResponse: {
      sessions: components["schemas"]["SessionListItem"][];
    };
    SignupRequest: {
      display_name?: string | null;
      email: string;
      password: string;
    };
    /** @description Returned when the user has TOTP enrolled — caller must complete the step-up flow. */
    StepUpResponse: {
      /** @description The MFA method required, e.g. `"totp"`. */
      step_up_required: string;
      /** @description Short-lived signed token to present when completing the step-up. */
      step_up_token: string;
    };
    OrgBody: {
      /** Format: uuid */
      id: string;
      name: string;
      slug: string;
    };
    TokenResponse: {
      access_token: string;
      /**
       * Format: int32
       * @description Lifetime in seconds.
       */
      expires_in: number;
      token_type: string;
    };
    TraceResponse: {
      allowed: boolean;
      subjects: components["schemas"]["ExpandSubject"][];
    };
    UpdateCredentialRequest: {
      nickname: string;
    };
    UpdateUser: {
      image_url?: string | null;
      display_name?: string | null;
    };
    UserBody: {
      image_url?: string | null;
      /** Format: date-time */
      created_at: string;
      display_name?: string | null;
      /** Format: uuid */
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthzResponse"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthzResponse"];
        };
      };
    };
  };
  ensure_partition: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Object type to partition (e.g. "document") */
        object_type: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Partition exists (created or already present) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid object_type identifier */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  check_permission: {
    parameters: {
      query: {
        /** @description Explicit subject to check as. Defaults to the current session user. */
        user?: string | null;
        permission: string;
        resource_type: string;
        resource_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown resource/permission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  expand_relation: {
    parameters: {
      query: {
        object_type: string;
        object_id: string;
        relation: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExpandResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  lookup_objects: {
    parameters: {
      query: {
        user?: string | null;
        permission: string;
        resource_type: string;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LookupResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  write_relation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelationRequest"];
      };
    };
    responses: {
      /** @description Relation written */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_relation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelationRequest"];
      };
    };
    responses: {
      /** @description Relation deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Relation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batch_relations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_schema: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": null | components["schemas"]["AuthzSchema"];
        };
      };
    };
  };
  put_schema: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthzSchema"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthzSchema"];
        };
      };
      /** @description Schema invalid */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  why_check: {
    parameters: {
      query: {
        user: string;
        permission: string;
        resource_type: string;
        resource_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TraceResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_emails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailRecord"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  add: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OttTokenResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirm_verification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmVerificationRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            components["schemas"]["ConfirmVerificationResponse"];
        };
      };
      /** @description Invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  make_primary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email set as primary */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email not found or not verified */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot remove primary email */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_verification: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OttTokenResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email not found or already verified */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  jwks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          /** @description public, max-age=3600, must-revalidate */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JwkSet"];
        };
      };
    };
  };
  create_magic_link: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MagicLinkRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MagicLinkResponse"];
        };
      };
      /** @description No account with that email */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  apple_callback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded":
          components["schemas"]["AppleCallbackForm"];
      };
    };
    responses: {
      /** @description Redirect to redirect_url with token and expires_at query params */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid state or Apple error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authorize: {
    parameters: {
      query: {
        /** @description URL to redirect to after authentication */
        redirect_url: string;
      };
      header?: never;
      path: {
        /** @description OAuth provider slug, e.g. `github`, `google` */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to OAuth provider */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Provider not configured */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  callback: {
    parameters: {
      query: {
        /** @description Authorization code from provider */
        code: string;
        /** @description PKCE state JWT */
        state: string;
      };
      header?: never;
      path: {
        /** @description OAuth provider slug */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to redirect_url with token and expires_at query params */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid state or provider error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  begin_passkey_authentication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BeginResponse"];
        };
      };
    };
  };
  begin_passkey_registration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BeginResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_passkeys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CredentialRecord"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_passkey: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FinishRegistrationRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisteredCredential"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_passkey: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Credential ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Credential deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_passkey: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Credential ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCredentialRequest"];
      };
    };
    responses: {
      /** @description Credential updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasswordResetResponse"];
        };
      };
      /** @description No account with that email or no password identity */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionsResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description MFA step-up required */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepUpResponse"];
        };
      };
      /** @description Session created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid credentials or token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentSessionResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Session ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  issue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description JWT not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  begin_enrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EnrollmentResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  disable: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description TOTP disabled */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirm_enrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmRequest"];
      };
    };
    responses: {
      /** @description TOTP enrollment confirmed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUser"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
