/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["healthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/authz/subjects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all subjects who hold the given relation on an object.
     *     Resolves subject sets recursively. Admin-only — use GET /v1/authz/subjects
     *     for the permission-scoped view available to authenticated users.
     */
    get: operations["list_subjects_expand"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_admin_config"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["patch"];
    trace?: never;
  };
  "/v1/admin/impersonations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_impersonation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_by_id"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/users/{id}/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke all active sessions for a user. Idempotent — safe to call when the user
     *     has no sessions.
     */
    delete: operations["delete_sessions"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/checks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Check multiple permissions in a single request. When the parallel-batch pgrx extension
     *     is loaded, single-hop checks are expanded into atomic (subject, relation, object_type,
     *     object_id) tuples and evaluated in one BFS issuing D+1 SQL queries — independent of N.
     *     Multi-hop permissions and deployments without the extension fall back to UNNEST grouping
     *     (same path as POST /v1/authz/decisions).
     */
    post: operations["post_checks"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check whether the current session user (or an explicit user) has a permission
     *     on a resource. Uses a bundled session-validation + authz CTE for one DB round-trip
     *     when checking the current session user.
     */
    get: operations["check_permission"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/objects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all objects of the given type that the current user (or an explicit user)
     *     can access via the resolved roles for a permission. Includes both direct role
     *     assignments and access granted via parent hierarchy.
     */
    get: operations["list_objects"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/relations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Write a single relation tuple. Idempotent — duplicate writes are silently ignored. */
    post: operations["write_relation"];
    /** Delete a single relation tuple. */
    delete: operations["delete_relation"];
    options?: never;
    head?: never;
    /** Batch write and/or delete relation tuples in a single transaction. */
    patch: operations["batch_relations"];
    trace?: never;
  };
  "/v1/authz/schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the current authz schema. Returns null if authz is not enabled. */
    get: operations["get_schema"];
    /**
     * Replace the authz schema. Validates and compiles before persisting.
     *     Setting schema to a valid document enables authz; this is the only way to enable it.
     */
    put: operations["put_schema"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/subjects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all subjects with a given permission on a resource. Resolves through the
     *     schema's role hierarchy to return every subject who can exercise the permission.
     *     Only direct role assignments are expanded; access via parent hierarchy is not
     *     included (use GET /v1/authz/objects from the subject's perspective for that).
     */
    get: operations["list_subjects"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/authz/traces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Explain why a permission check returned its result. Runs expand on all direct
     *     role relations and reports which subjects appear, letting you trace a grant or
     *     denial. Note: access granted purely via parent hierarchy is not reflected here.
     */
    get: operations["why_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_emails"];
    put?: never;
    post: operations["add"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/verifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["confirm_verification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["make_primary"];
    post?: never;
    delete: operations["remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/emails/{id}/verifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_verification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/identities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_identities"];
    put?: never;
    post: operations["add_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/identities/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["unlink"];
    options?: never;
    head?: never;
    patch: operations["update"];
    trace?: never;
  };
  "/v1/invitations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["view_invitation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/invitations/{id}/acceptances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["accept_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/invitations/{id}/declinations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["decline_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/jwks.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["jwks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_keys"];
    put?: never;
    post: operations["create_key"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/keys/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_key"];
    put?: never;
    post?: never;
    delete: operations["delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/magic-links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_magic_link"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/apple/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["apple_callback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["authorize"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/oauth/{provider}/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orgs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_orgs"];
    put?: never;
    post: operations["create_org"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orgs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_org"];
    put?: never;
    post?: never;
    delete: operations["delete_org"];
    options?: never;
    head?: never;
    patch: operations["update_org"];
    trace?: never;
  };
  "/v1/orgs/{id}/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_invitations"];
    put?: never;
    post: operations["create_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orgs/{id}/invitations/{inv_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["revoke_invitation"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orgs/{id}/invitations/{inv_id}/resends": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["resend_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orgs/{id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_members"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orgs/{id}/members/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["remove_member"];
    options?: never;
    head?: never;
    patch: operations["update_member"];
    trace?: never;
  };
  "/v1/passkey-authentications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["begin_passkey_authentication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/passkey-registrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["begin_passkey_registration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/passkeys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_passkeys"];
    put?: never;
    post: operations["create_passkey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/passkeys/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_passkey"];
    options?: never;
    head?: never;
    patch: operations["update_passkey"];
    trace?: never;
  };
  "/v1/password-resets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_password_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_sessions"];
    put?: never;
    post: operations["login"];
    delete: operations["delete_all_sessions"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_current"];
    put?: never;
    post?: never;
    delete: operations["delete_current"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sessions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_by_id"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * POST /v1/tokens — issue a short-lived JWT access token.
     * @description Accepts any valid bearer credential in `Authorization`:
     *     - **Session token** (`session_…`) — issues JWT + a fresh refresh token.
     *     - **Refresh token** (`rt_…`) — rotates the refresh token and issues a new JWT.
     *     - **API key** (`key_…`) — issues JWT only (no refresh token).
     *
     *     Requires `jwt_enabled = true` in app_config; returns 400 otherwise.
     *     An optional JSON body may carry `claims` — a flat object of key/value pairs
     *     merged into the JWT payload after all reserved claims are set.
     */
    post: operations["issue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/totp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["begin_enrollment"];
    delete: operations["disable"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/totp/confirmations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["confirm_enrollment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/totp/recovery-codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["regenerate_recovery_codes"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_me"];
    put?: never;
    post?: never;
    delete: operations["delete_me"];
    options?: never;
    head?: never;
    patch: operations["update_me"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddPasswordRequest: {
      password: string;
    };
    AddRequest: {
      email: string;
    };
    AdminUserResponse: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      deleted_at?: string | null;
      email?: string | null;
      /** Format: date-time */
      email_verified_at?: string | null;
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      primary_email_id: string;
      /** Format: uuid */
      primary_org_id: string;
    };
    AppleCallbackForm: {
      code: string;
      state: string;
      user?: string | null;
    };
    AuthResponse: {
      email: components["schemas"]["EmailBody"];
      org: components["schemas"]["OrgBody"];
      session: components["schemas"]["SessionBody"];
      user: components["schemas"]["UserBody"];
    };
    AuthorizeResponse: {
      /** @description Full OAuth authorization URL — navigate the browser here to start the flow. */
      url: string;
    };
    AuthzSchema: {
      resources: components["schemas"]["ResourceDef"][];
      subject_types?: string[];
      /** Format: int32 */
      version: number;
    };
    BatchRequest: {
      deletes?: components["schemas"]["RelationRequest"][];
      writes?: components["schemas"]["RelationRequest"][];
    };
    BatchResponse: {
      /** Format: int64 */
      deleted: number;
      /** Format: int64 */
      written: number;
    };
    BeginResponse: {
      /** @description WebAuthn options object — pass directly to the browser's WebAuthn API. */
      options: Record<string, never>;
      /** @description Opaque state token; include in the corresponding finish request. */
      state_token: string;
    };
    CallbackResponse: {
      /** Format: date-time */
      expires_at: string;
      token: string;
    };
    CheckResponse: {
      allowed: boolean;
    };
    ChecksItem: {
      permission: string;
      resource_id: string;
      resource_type: string;
      /** @description Explicit subject to check as. Defaults to the current session user. */
      user?: string | null;
    };
    ChecksRequest: {
      checks: components["schemas"]["ChecksItem"][];
    };
    ChecksResponse: {
      /** @description Results in the same order as the input checks. */
      results: boolean[];
    };
    ConfigResponse: {
      jwt_enabled: boolean;
      /** Format: int32 */
      session_idle_timeout_seconds?: number | null;
    };
    ConfirmRequest: {
      code: string;
    };
    ConfirmVerificationRequest: {
      token: string;
    };
    ConfirmVerificationResponse: {
      /** Format: date-time */
      verified_at: string;
    };
    CreateInvitationRequest: {
      email?: string | null;
      role: string;
    };
    CreateOrgRequest: {
      metadata?: unknown;
      name: string;
      slug?: string | null;
    };
    CreateRequest: {
      /**
       * Format: date-time
       * @description When the key expires. Defaults to 100 years from now (effectively never).
       */
      expires_at?: string | null;
      name: string;
    };
    /** @description Returned only on creation — the `key` field is never shown again. */
    CreateResponse: components["schemas"]["Key"] & {
      /** @description The full bearer token. Store it now — it cannot be retrieved later. */
      key: string;
    };
    CredentialRecord: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      last_used_at?: string | null;
      nickname?: string | null;
    };
    CurrentSessionResponse: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      ip_address?: string | null;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: uuid */
      token_id: string;
      user_agent?: string | null;
    };
    EmailBody: {
      email: string;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      verified_at?: string | null;
    };
    EmailRecord: {
      email: string;
      /** Format: uuid */
      id: string;
      is_primary: boolean;
      /** Format: date-time */
      verified_at?: string | null;
    };
    EnrollmentResponse: {
      /** Format: uuid */
      factor_id: string;
      provisioning_uri: string;
      qr_data_url: string;
      recovery_codes: string[];
      secret_b32: string;
    };
    /** @description Wire-format error body returned on all non-2xx responses. */
    ErrorBody: {
      /** @description Machine-readable error code, e.g. `"invalid_credentials"`. */
      code: string;
      /** @description Human-readable description. */
      message: string;
    };
    /** @description Top-level error envelope for all API error responses. */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    FinishRegistrationRequest: {
      /** @description WebAuthn `PublicKeyCredential` response from the browser. */
      credential: Record<string, never>;
      nickname?: string | null;
      state_token: string;
    };
    HealthzResponse: {
      status: string;
      version: string;
    };
    HierarchyDef: {
      /** @description The relation name on this resource that points to parent objects. */
      parent_relation: string;
      /** @description The resource type of the parent. */
      parent_resource: string;
    };
    IdentitiesResponse: {
      identities: components["schemas"]["IdentityItem"][];
    };
    IdentityItem: {
      /** Format: date-time */
      created_at: string;
      /** @description Human-readable label: email address for password identities, provider slug for OAuth. */
      display: string;
      /** Format: uuid */
      id: string;
      provider: string;
    };
    ImpersonateRequest: {
      /**
       * Format: uuid
       * @description The ID of the user to impersonate.
       */
      user_id: string;
    };
    InvitationResponse: {
      /** Format: date-time */
      created_at: string;
      email?: string | null;
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      org_id: string;
      role: string;
      /** @description Plaintext token — only present on creation, never returned again. */
      token?: string | null;
    };
    InvitationViewResponse: {
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      org_id: string;
      org_name: string;
      role: string;
    };
    InvitationsResponse: {
      has_more: boolean;
      invitations: components["schemas"]["InvitationResponse"][];
      next_page?: string | null;
    };
    IssueRequest: {
      /**
       * @description Arbitrary JSON object merged into the JWT payload.
       *     Reserved keys (`sub`, `iss`, `aud`, `iat`, `nbf`, `exp`, `jti`,
       *     `impersonated`) are always overwritten by the service and cannot be
       *     supplied here.
       */
      claims?: {
        [key: string]: unknown;
      } | null;
    };
    Jwk: {
      alg: string;
      crv: string;
      kid: string;
      kty: string;
      use: string;
      x: string;
    };
    JwkSet: {
      keys: components["schemas"]["Jwk"][];
    };
    Key: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      last_used_at?: string | null;
      name: string;
    };
    KeysResponse: {
      keys: components["schemas"]["Key"][];
    };
    LinkCallbackResponse: {
      linked: boolean;
    };
    LoginRequest:
      | {
        email: string;
        /** @enum {string} */
        grant_type: "password";
        password: string;
      }
      | {
        /** @enum {string} */
        grant_type: "magic_link";
        token: string;
      }
      | {
        /** @enum {string} */
        grant_type: "password_reset";
        new_password: string;
        token: string;
      }
      | {
        /** @enum {string} */
        grant_type: "email_change";
        token: string;
      }
      | {
        code: string;
        /** @enum {string} */
        grant_type: "totp_step_up";
        step_up_token: string;
      }
      | {
        code: string;
        /** @enum {string} */
        grant_type: "totp_recovery";
        step_up_token: string;
      }
      | {
        credential: Record<string, never>;
        /** @enum {string} */
        grant_type: "passkey";
        state_token: string;
      };
    MagicLinkRequest: {
      email: string;
    };
    MagicLinkResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to exchange via `POST /v1/sessions` with `grant_type=magic_link`. */
      token: string;
    };
    MeResponse: {
      email: components["schemas"]["EmailBody"];
      org: components["schemas"]["OrgBody"];
      user: components["schemas"]["UserBody"];
    };
    MemberResponse: {
      /** Format: date-time */
      joined_at: string;
      role: string;
      /** Format: uuid */
      user_id: string;
    };
    MembersResponse: {
      has_more: boolean;
      members: components["schemas"]["MemberResponse"][];
      next_page?: string | null;
    };
    ObjectsResponse: {
      has_more: boolean;
      next_page?: string | null;
      object_ids: string[];
    };
    OrgBody: {
      /** Format: uuid */
      id: string;
      image_url?: string | null;
      name: string;
      slug: string;
    };
    OrgResponse: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      image_url?: string | null;
      metadata: unknown;
      name: string;
      slug: string;
    };
    OrgsResponse: {
      has_more: boolean;
      next_page?: string | null;
      orgs: components["schemas"]["OrgResponse"][];
    };
    OttTokenResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to use in the corresponding session grant. */
      token: string;
    };
    PasswordResetRequest: {
      email: string;
    };
    PasswordResetResponse: {
      /** Format: date-time */
      expires_at: string;
      /** @description One-time token to exchange via `POST /v1/sessions` with `grant_type=password_reset`. */
      token: string;
    };
    RecoveryCodesResponse: {
      recovery_codes: string[];
    };
    RegisteredCredential: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      nickname?: string | null;
    };
    RelationObject: {
      id: string;
      type: string;
    };
    RelationRequest: {
      object: components["schemas"]["RelationObject"];
      relation: string;
      subject: components["schemas"]["RelationSubject"];
    };
    RelationSubject: {
      id: string;
      relation?: string | null;
      type?: string | null;
    };
    ResourceDef: {
      hierarchy?: null | components["schemas"]["HierarchyDef"];
      name: string;
      permissions: {
        [key: string]: string[];
      };
      role_inheritance?: components["schemas"]["RoleEdge"][];
      roles: string[];
    };
    RoleEdge: {
      inferior: string;
      superior: string;
    };
    SessionBody: {
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      /** @description Opaque bearer token — store securely, transmit as `Authorization: Bearer <token>`. */
      token: string;
    };
    SessionListItem: {
      /** Format: date-time */
      created_at: string;
      /** @description Whether this is the caller's current session. */
      current: boolean;
      /** Format: date-time */
      expires_at: string;
      /** Format: uuid */
      id: string;
      ip_address?: string | null;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: uuid */
      token_id: string;
      user_agent?: string | null;
    };
    SessionsResponse: {
      sessions: components["schemas"]["SessionListItem"][];
    };
    SignupRequest: {
      display_name?: string | null;
      email: string;
      password: string;
    };
    /** @description Returned when the user has TOTP enrolled — caller must complete the step-up flow. */
    StepUpResponse: {
      /** @description The MFA method required, e.g. `"totp"`. */
      step_up_required: string;
      /** @description Short-lived signed token to present when completing the step-up. */
      step_up_token: string;
    };
    Subject: {
      id: string;
      relation: string;
    };
    SubjectsResponse: {
      subjects: components["schemas"]["Subject"][];
    };
    TokenResponse: {
      access_token: string;
      /**
       * Format: int32
       * @description Access token lifetime in seconds.
       */
      expires_in: number;
      /**
       * @description Rotate-on-use refresh token. Present when authenticated via a session or
       *     a prior refresh token; absent for API-key auth.
       */
      refresh_token?: string | null;
      token_type: string;
    };
    TraceResponse: {
      allowed: boolean;
      subjects: components["schemas"]["Subject"][];
    };
    /**
     * @description Partial config update. Only fields explicitly set are updated.
     *     Send `"session_idle_timeout_seconds": null` to clear the idle timeout.
     */
    UpdateConfigRequest: {
      jwt_enabled?: boolean | null;
      /** Format: int32 */
      session_idle_timeout_seconds?: number | null;
    };
    UpdateCredentialRequest: {
      nickname: string;
    };
    UpdateIdentityRequest: {
      current_password: string;
      new_password: string;
    };
    UpdateMeRequest: {
      image_url?: string | null;
      metadata?: unknown;
      name?: string | null;
      slug?: string | null;
    };
    UpdateMemberRequest: {
      role: string;
    };
    UpdateOrgRequest: {
      image_url?: string | null;
      metadata?: unknown;
      name?: string | null;
      slug?: string | null;
    };
    UserBody: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      image_url?: string | null;
      metadata: unknown;
      name: string;
      /** Format: uuid */
      primary_org_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthzResponse"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthzResponse"];
        };
      };
    };
  };
  list_subjects_expand: {
    parameters: {
      query: {
        object_type: string;
        object_id: string;
        relation: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubjectsResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_admin_config: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateConfigRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_impersonation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImpersonateRequest"];
      };
    };
    responses: {
      /** @description Impersonation session created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  search: {
    parameters: {
      query?: {
        /** @description Look up by primary email address (case-insensitive). */
        email?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserResponse"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All sessions revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  post_checks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChecksRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChecksResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown resource/permission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  check_permission: {
    parameters: {
      query: {
        /** @description Explicit subject to check as. Defaults to the current session user. */
        user?: string | null;
        permission: string;
        resource_type: string;
        resource_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown resource/permission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_objects: {
    parameters: {
      query: {
        user?: string | null;
        permission: string;
        resource_type: string;
        limit?: number | null;
        after?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ObjectsResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown resource/permission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  write_relation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelationRequest"];
      };
    };
    responses: {
      /** @description Relation written */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_relation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelationRequest"];
      };
    };
    responses: {
      /** @description Relation deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Relation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batch_relations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_schema: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": null | components["schemas"]["AuthzSchema"];
        };
      };
    };
  };
  put_schema: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthzSchema"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthzSchema"];
        };
      };
      /** @description Schema invalid */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_subjects: {
    parameters: {
      query: {
        resource_type: string;
        resource_id: string;
        permission: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubjectsResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown resource/permission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  why_check: {
    parameters: {
      query: {
        user: string;
        permission: string;
        resource_type: string;
        resource_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TraceResponse"];
        };
      };
      /** @description Authz not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown resource/permission */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_emails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailRecord"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  add: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OttTokenResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirm_verification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmVerificationRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            components["schemas"]["ConfirmVerificationResponse"];
        };
      };
      /** @description Invalid or expired token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  make_primary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email set as primary */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email not found or not verified */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot remove primary email */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_verification: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OttTokenResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Email not found or already verified */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_identities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentitiesResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  add_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddPasswordRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityItem"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password identity already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  unlink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Identity ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot remove last auth method */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Identity ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateIdentityRequest"];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  view_invitation: {
    parameters: {
      query: {
        /** @description Plaintext invitation token */
        token: string;
      };
      header?: never;
      path: {
        /** @description Invitation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationViewResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  accept_invitation: {
    parameters: {
      query: {
        /** @description Plaintext invitation token */
        token: string;
      };
      header?: never;
      path: {
        /** @description Invitation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invitation not found or expired */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Already a member */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  decline_invitation: {
    parameters: {
      query: {
        /** @description Plaintext invitation token */
        token: string;
      };
      header?: never;
      path: {
        /** @description Invitation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invitation not found or expired */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  jwks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          /** @description public, max-age=3600, must-revalidate */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JwkSet"];
        };
      };
    };
  };
  list_keys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeysResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_key: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRequest"];
      };
    };
    responses: {
      /** @description Key created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_key: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Key ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Key"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Key ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Key revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_magic_link: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MagicLinkRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MagicLinkResponse"];
        };
      };
      /** @description No account with that email */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  apple_callback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded":
          components["schemas"]["AppleCallbackForm"];
      };
    };
    responses: {
      /** @description Link — identity added to existing account */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LinkCallbackResponse"];
        };
      };
      /** @description Invalid state or Apple error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authorize: {
    parameters: {
      query: {
        /** @description URL to redirect to after authentication */
        redirect_url: string;
      };
      header?: never;
      path: {
        /** @description OAuth provider slug, e.g. `github`, `google` */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthorizeResponse"];
        };
      };
      /** @description Provider not configured */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  callback: {
    parameters: {
      query: {
        /** @description Authorization code from provider */
        code: string;
        /** @description PKCE state JWT */
        state: string;
      };
      header?: never;
      path: {
        /** @description OAuth provider slug */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Link — identity added to existing account */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LinkCallbackResponse"];
        };
      };
      /** @description Invalid state or provider error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description OAuth identity already claimed by another user */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_orgs: {
    parameters: {
      query?: {
        after?: string | null;
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrgsResponse"];
        };
      };
    };
  };
  create_org: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrgRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrgResponse"];
        };
      };
      /** @description Slug already taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_org: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrgResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_org: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot delete personal org */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_org: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateOrgRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrgResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Slug already taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_invitations: {
    parameters: {
      query?: {
        after?: string | null;
        limit?: number | null;
      };
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationsResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_invitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInvitationRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Pending invite for this email already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  revoke_invitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
        /** @description Invitation ID */
        inv_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  resend_invitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
        /** @description Invitation ID */
        inv_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_members: {
    parameters: {
      query?: {
        after?: string | null;
        limit?: number | null;
      };
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MembersResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
        /** @description User ID of the member */
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Would remove last owner */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Org ID */
        id: string;
        /** @description User ID of the member */
        member_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMemberRequest"];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Would remove last owner */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  begin_passkey_authentication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BeginResponse"];
        };
      };
    };
  };
  begin_passkey_registration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BeginResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_passkeys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CredentialRecord"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_passkey: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FinishRegistrationRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisteredCredential"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_passkey: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Credential ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Credential deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_passkey: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Credential ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCredentialRequest"];
      };
    };
    responses: {
      /** @description Credential updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PasswordResetResponse"];
        };
      };
      /** @description No account with that email or no password identity */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionsResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description MFA step-up required */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepUpResponse"];
        };
      };
      /** @description Session created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid credentials or token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_all_sessions: {
    parameters: {
      query?: {
        /**
         * @description When true, the current session is preserved; all other sessions are revoked.
         *     Defaults to false — all sessions including the current one are revoked.
         */
        except_current?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sessions revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentSessionResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Session ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  issue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IssueRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description JWT not enabled */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  begin_enrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EnrollmentResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  disable: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description TOTP disabled */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  confirm_enrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmRequest"];
      };
    };
    responses: {
      /** @description TOTP enrollment confirmed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  regenerate_recovery_codes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecoveryCodesResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description No enrolled TOTP factor */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Password validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMeRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Slug already taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
