[tools]
dprint = "latest"
node = "lts"
rust = { version = "1.92", components = "rustfmt,clippy" }
yamlfmt = "latest"
cargo-binstall = "latest"
"cargo:sqlx-cli" = "latest"

[tasks."format"]
run = "dprint fmt"

[tasks."sqlx:prepare"]
run = "cargo run --package xtask"
