[tools]
dprint = "latest"
node = "lts"
rust = { version = "1.92", components = "rustfmt,clippy" }
yamlfmt = "latest"
cargo-binstall = "latest"
"cargo:sqlx-cli" = "latest"

[tasks."format"]
run = "dprint fmt"

[tasks."sqlx:prepare"]
run = "cargo run --package xtask"

[tasks."openapi:generate"]
run = "cargo run -- generate-openapi"

[tasks."sdk:generate-types"]
run = ["cd ts && node scripts/generate-types.mjs"]
dir = "sdk"
depends = ["openapi:generate"]
